package com.aaa.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SecondaryTable;
import javax.persistence.Table;
import javax.persistence.Transient;

//@SecondaryTable(name="user_log_in", pkJoinColumns= @PrimaryKeyJoinColumn(name="user_id"))
@Entity
@Table(name = "user_profile")
public class UserProfile {
	
	@Id    
	@GeneratedValue(strategy = GenerationType.IDENTITY)//AutoGenerated
	@Column(name="user_id")//PK
	private Long id;// 1
	
//  ============ Relationship Mappings ============	
	
	@ManyToOne
	@JoinColumn(name="user_type_id", referencedColumnName="user_type_id")// Sharing above idOfEachUserProfile with Table("user_type_id")
	private UserType userType;
	
	@OneToOne(mappedBy="userProfile", cascade=CascadeType.ALL)
	@PrimaryKeyJoinColumn
	private Login login;
	
	@Transient
	private String username;
	
	@Transient
	private String password;
	
	@Transient
	private int oTP;
	
	@Column(name="first_name")
	private String firstName;// 2
	
	@Column(name="last_name")
	private String lastName;// 3
	
	@Column(name="email")
	private String email;// 4
	
	@Column(name="gender")
	private String gender;// 5
	
	@Column(name="birthday")
	private String birthday;// 6
	
	@Column(name="country")
	private String country;// 7
	
	@Column(name="city")
	private String city;// 8
	
	@Column(name="marital_status_id")
	private int maritalStatusId;// 9
	
	@Column(name="likes")
	private int likes;
	
//  ============ Transient Attributes ============	
	
	@Transient
	@Column(name="create_date")
	private String userCreatedTimeStamp; // 10
	
	@Transient
	@Column(name="last_profile_edit")
	private String userLastEditTimeStamp;// 11
	
	@Transient
	private String confirmPassword;
	
//  ============ JoinTable Attributes ============
	
	@Transient
	private int userTypeId;
	
	@Transient
	private String userTypeName;
	
//  ============ Getters & Setters ============	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public int getMaritalStatusId() {
		return maritalStatusId;
	}

	public void setMaritalStatusId(int maritalStatusId) {
		this.maritalStatusId = maritalStatusId;
	}

	public String getUserCreatedTimeStamp() {
		return userCreatedTimeStamp;
	}

	public void setUserCreatedTimeStamp(String userCreatedTimeStamp) {
		this.userCreatedTimeStamp = userCreatedTimeStamp;
	}

	public String getUserLastEditTimeStamp() {
		return userLastEditTimeStamp;
	}

	public void setUserLastEditTimeStamp(String userLastEditTimeStamp) {
		this.userLastEditTimeStamp = userLastEditTimeStamp;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}



	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getUserTypeId() {
		return userTypeId;
	}

	public void setUserTypeId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	public String getUserTypeName() {
		return userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	public UserType getUserType() {
		return userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
	}

	public Login getLogin() {
		return login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	

	public int getoTP() {
		return oTP;
	}

	public void setoTP(int oTP) {
		this.oTP = oTP;
	}

	public int getLikes() {
		return likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	@Override
	public String toString() {
		return "UserProfile [id=" + id + ", userType=" + userType + ", login=" + login + ", username=" + username
				+ ", password=" + password + ", oTP=" + oTP + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", email=" + email + ", gender=" + gender + ", birthday=" + birthday + ", country=" + country
				+ ", city=" + city + ", maritalStatusId=" + maritalStatusId + ", likes=" + likes
				+ ", userCreatedTimeStamp=" + userCreatedTimeStamp + ", userLastEditTimeStamp=" + userLastEditTimeStamp
				+ ", confirmPassword=" + confirmPassword + ", userTypeId=" + userTypeId + ", userTypeName="
				+ userTypeName + "]";
	}
}
